/* Pet creation types */
export const PET_CREATION_PENDING = 'PET_CREATION_PENDING';
export const PET_CREATION_SUCCESS = 'PET_CREATION_SUCCESS';
export const PET_CREATION_FAILURE = 'PET_CREATION_FAILURE';
